# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Rohan Nagar
paginate:       5
baseurl:        ""
url:            "https://rohannagar.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Rohan Nagar
  url:          https://rohannagar.github.io
  email:        rohannagar11@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
