# Site settings
title: Rohan Nagar
email: rohannagar11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Life from the perspective of a UT Austin student.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rohannagar.github.io" # the base hostname & protocol for your site
twitter_username: RohanNagar22
github_username: RohanNagar

# Build settings
markdown: redcarpet
