# Site settings
title: Rohan Nagar
description: "Your favorite engineer."
analytics: # Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> # use this in posts to define how long the preview of the blog post is

colors:
  primary: "#00b3fe"
  primary_rgb: "0,179,254" # Needed in some places for the transparency effect.
  secondary: "#384452"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Social network usernames
social:
  - title: facebook
    url: https://www.facebook.com/rnagar
  - title: twitter
    url: https://twitter.com/RohanNagar22
  - title: instagram
    url: https://www.instagram.com/rnagar95
  - title: linkedin
    url: https://www.linkedin.com/in/rohannagar
  - title: google-plus
    url: https://plus.google.com/u/0/+RohanNagar22
  - title: github
    url: https://github.com/RohanNagar
